### ISSUE TITLE
EXC_BAD_INSTRUCTION on AES:218

### ISSUE THREAD

**Issue by bbsan2k** [krzyzanowskim/CryptoSwift#32]
Hi, 
Currently facing in issue in CryptoSwift, AES line 218.

This is my code:

    case let (.Some(data), .Some(iv), .Some(iter), .Some(salt), .Some(aes)):
				let (aesPassword, it) = generateAesKeyForPassword(aes, salt: (salt as  String).dataUsingEncoding(NSUTF8StringEncoding)!, roundCount: iter as Int, error: &error)!

				let passString = aesPassword.base64EncodedStringWithOptions(.allZeros)
				let iv_data = (iv as String).dataUsingEncoding(NSUTF8StringEncoding)!
				
				
				let decryptedData = Cipher.AES(key: aesPassword, iv: iv_data, blockMode: .CBC).decrypt((data as String).dataUsingEncoding(NSUTF8StringEncoding)!)

				
				
I'm not sure, what causes this issue. The Data I'm trying to decode was encoded with openssl on rails. 
iv_data and passString are both valid.

**Comment by krzyzanowskim** [comment]
this is master branch?

**Comment by bbsan2k** [comment]
I think so, I included this in my podfile:
    pod 'CryptoSwift'

**Comment by krzyzanowskim** [comment]
I can't tell without input data. It may be one of the assertion for input parameters.

passString is never used. I don't know what is result of `generateAesKeyForPassword`. Please separate usecase for Playground.

**Comment by bbsan2k** [comment]
Oh, seems I have figured it out. Looks like there was an initialization Problem for the Cipher, so there was a NullPointer. Not sure what caused this. Init with AES() though works.
Now I'm experiencing another problem with my IV, as it has half the size of my key. Encryption on ruby works correctly, but decryption now seems to be an issue :(

**Comment by krzyzanowskim** [comment]
Depends what ruby code is doing with this IV, it may be that it expand it with zeroes at the end to size of key, try can try this.

**Comment by bbsan2k** [comment]
Doesn't the IV need to match the AESBlockSize and not the Keysize?

**Comment by krzyzanowskim** [comment]
yes! 👏  need to fix this. If IV is longer than block size, decryption using CBC andCFB is broken. Wo temporary workaround this issue you can use AES-128 to check the flow.

**Comment by krzyzanowskim** [comment]
Ok, should be fixed now.

**Comment by bbsan2k** [comment]
Thanks a lot ;)

**Comment by krzyzanowskim** [comment]
can you confir on your side?

**Comment by bbsan2k** [comment]
I'll try tomorrow, but I think there's still an issue in AES.swift:116 as the IV is shorter (16bytes) than an 256-Key (32bytes)

**Comment by krzyzanowskim** [comment]
ok, fixed on branches.

**Comment by bbsan2k** [comment]
Yes!!! It definitely works ;) Thanks a lot! I issued a pull request for an updated podspec, hope this was ok?

**Comment by krzyzanowskim** [comment]
do you mind share Ruby part here ?
