### ISSUE TITLE
Cant solve newest update about NSData and [UInt8]

### ISSUE THREAD

**Issue by azisseno** [krzyzanowskim/CryptoSwift#51]
Please help me,..
I already read the newest update of Cryptoswift for xcode 6.3 
But I still cant solve my problem... 

![screen shot 2015-04-13 at 10 54 38 am](https://cloud.githubusercontent.com/assets/11918388/7109853/1801f0c0-e1d1-11e4-9612-4601556bc58d.png)

And about converting between NSData and [UInt8]
When i use this code 

let bytes = data.bytes()

It always error:
Invalid use of '()' to call a value of non-function type 'UnsafePointer<Void>

Can you suggest what should I do to solve this problem..
or what's wrong with my code ? :(

**Comment by krzyzanowskim** [comment]
hm.. NSData.bytes() should be available with extenstion to NSData. Can you please create small sample problem where the issue is reproducible? maybe it is project setting or smth.

**Comment by azisseno** [comment]
This is the sample .. i copy your code.. 
![screen shot 2015-04-13 at 1 22 28 pm](https://cloud.githubusercontent.com/assets/11918388/7110678/cb21a78c-e1df-11e4-8c31-76553d770f14.png)


And this one my project setting
![screen shot 2015-04-13 at 1 22 45 pm](https://cloud.githubusercontent.com/assets/11918388/7110682/d7bbfa7e-e1df-11e4-8678-9d4d4bdd2dfd.png)

Why cant i use that NSData.bytes() function :(
I Installed cryptoswift from github..

**Comment by krzyzanowskim** [comment]
ok, Ill investigate

**Comment by azisseno** [comment]
Thanks, sir..

**Comment by Luke47** [comment]
FYI: The .bytes() function seems not to be public. I fixed the issue by implementing my own version below the bytes() function:

public func convertToBytes() -> [UInt8] {
        let count = self.length / sizeof(UInt8)
        var bytesArray = [UInt8](count: count, repeatedValue: 0)
        self.getBytes(&bytesArray, length:count * sizeof(UInt8))
        return bytesArray
    }

**Comment by azisseno** [comment]
@Luke47 Thanks... that work ..

Now the problem.. what's new with randomIV... ??
On previous version.. i wrote =>

        let ivData:NSData = NSData.withBytes(Cipher.randomIV(keyData))
        let cipherdata = Cipher.AES(key: keyData, iv: ivData, blockMode: .CBC).encrypt(plaintextData)

Work fine .....

But now ... 
It's getting error...

"Cannot invoke 'randomIV' with argument list of type'(NSData)''
"Cannot invoke 'encrypt' with an argument list of type '(NSData)'"

**Comment by Luke47** [comment]
It seems some functions now require different parameter types. E.g. "randomIV" needs blockSize:Int now. Just have a look at the specific functions you want to use :)

**Comment by azisseno** [comment]
@Luke47 Get it ... seems like i missed that... 

I changed 

let ivData:NSData = NSData.withBytes(Cipher.randomIV(keyData))
to
        let ivData:NSData = NSData.withBytes(Cipher.randomIV(count(keyData.convertToBytes())))

It work fine now ... 


But. I'm still getting error with this
        let cipherdata = Cipher.AES(key: keyData, iv: ivData, blockMode: .CBC).encrypt(plainText)

"Cannot invoke 'encrypt' with an argument list of type '(NSData)'"

I change the parameter to String, [UInt8] and NString... 

But it doesnt work ...

**Comment by krzyzanowskim** [comment]
There is compiler ambiguity issue involved. I have to change name of this function.

**Comment by azisseno** [comment]
@krzyzanowskim 

Yes., Anyway what should i do with this

**Comment by krzyzanowskim** [comment]
Wait for update.

**Comment by azisseno** [comment]
@krzyzanowskim  thanks, sir.. :)

**Comment by krzyzanowskim** [comment]
Fix is available on branch "develop". New release will be available shortly.

**Comment by krzyzanowskim** [comment]
New version 0.0.10 is available with fix for this issue. For now on to convert from NSData to [UInt8] please use `data.arrayOfBytes()`
